apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: KEK-PROJECT-dev
  namespace: argocd
  labels:
    env: dev
    project: KEK-PROJECT
spec:
  project: default
  source:
    repoURL: 'https://github.com/Evogene1/teamcity_argocd.git'
    targetRevision: main
    path: apps/overlays/dev/KEK-PROJECT
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
