apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kek-project
  namespace: argocd
spec:
  description: "Project for kek-project"
  sourceRepos:
  - "*"
  destinations:
  - namespace: service
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
