apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kek-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: kek-app
    app.kubernetes.io/instance: kek-app-dev
    app.kubernetes.io/part-of: kek-project
    app.kubernetes.io/managed-by: argocd
    environment: dev
    version: "1.0.2"
spec:
  project: kek-project
  source:
    repoURL: 'https://github.com/Evogene1/teamcity_argocd.git'
    targetRevision: main
    path: apps/overlays/dev/kek-project/kek-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
