apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: billing-proj
  namespace: argocd
spec:
  description: Project for billing-proj in dev
  sourceRepos: ["*"]
  destinations:
  - namespace: billing-ns
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
