apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kek-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: "Project for kek-project management"
  sourceRepos: ["*"]
  destinations:
  - namespace: service
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
