apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service

resources:
  - ../../../../base/kek-app/deployment.yml
  - ../../../../base/kek-app/service.yml
  - ../../../../base/kek-app/ingress.yml

patches:
  - path: deployment-patch.yml
  - path: ingress-patch.yml
