apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: service
resources:
  - ../../../../base/kek-app
images:
  - name: gen921/hw07
    newTag: "1.0.1"
  - deployment-kek-app.yml
