apiVersion: apps/v1
kind: Deployment
metadata:
  name: generic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic-app
  template:
    metadata:
      labels:
        app: generic-app
    spec:
      containers:
      - name: main-container
        image: placeholder:latest